/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CvInput {
        /**
          * Label of the input
         */
        "label": string;
        /**
          * Name of the input
         */
        "name": string;
        /**
          * Placeholder of the input
         */
        "placeholder": string;
        /**
          * Type of the input
         */
        "type": string;
        /**
          * Value of the input
         */
        "value": string;
    }
    interface CvSelect {
        "label": string;
        "name": string;
    }
    interface CvTextarea {
        /**
          * Label of the textarea
         */
        "label": string;
        /**
          * Name of the textarea
         */
        "name": string;
        /**
          * Placeholder of the textarea
         */
        "placeholder": string;
        /**
          * Value of the textarea
         */
        "value": string;
    }
}
declare global {
    interface HTMLCvInputElement extends Components.CvInput, HTMLStencilElement {
    }
    var HTMLCvInputElement: {
        prototype: HTMLCvInputElement;
        new (): HTMLCvInputElement;
    };
    interface HTMLCvSelectElement extends Components.CvSelect, HTMLStencilElement {
    }
    var HTMLCvSelectElement: {
        prototype: HTMLCvSelectElement;
        new (): HTMLCvSelectElement;
    };
    interface HTMLCvTextareaElement extends Components.CvTextarea, HTMLStencilElement {
    }
    var HTMLCvTextareaElement: {
        prototype: HTMLCvTextareaElement;
        new (): HTMLCvTextareaElement;
    };
    interface HTMLElementTagNameMap {
        "cv-input": HTMLCvInputElement;
        "cv-select": HTMLCvSelectElement;
        "cv-textarea": HTMLCvTextareaElement;
    }
}
declare namespace LocalJSX {
    interface CvInput {
        /**
          * Label of the input
         */
        "label"?: string;
        /**
          * Name of the input
         */
        "name"?: string;
        /**
          * Placeholder of the input
         */
        "placeholder"?: string;
        /**
          * Type of the input
         */
        "type"?: string;
        /**
          * Value of the input
         */
        "value"?: string;
    }
    interface CvSelect {
        "label"?: string;
        "name"?: string;
    }
    interface CvTextarea {
        /**
          * Label of the textarea
         */
        "label"?: string;
        /**
          * Name of the textarea
         */
        "name"?: string;
        /**
          * Placeholder of the textarea
         */
        "placeholder"?: string;
        /**
          * Value of the textarea
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "cv-input": CvInput;
        "cv-select": CvSelect;
        "cv-textarea": CvTextarea;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv-input": LocalJSX.CvInput & JSXBase.HTMLAttributes<HTMLCvInputElement>;
            "cv-select": LocalJSX.CvSelect & JSXBase.HTMLAttributes<HTMLCvSelectElement>;
            "cv-textarea": LocalJSX.CvTextarea & JSXBase.HTMLAttributes<HTMLCvTextareaElement>;
        }
    }
}
